on:
  push:
    branches:
      - main

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy to OVH via FTP
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }} # serveur FTP OVH
          username: ${{ secrets.FTP_USERNAME }} # nom d'utilisateur FTP
          password: ${{ secrets.FTP_PASSWORD }} # mot de passe FTP
          protocol: ftp
          local-dir: ./
          server-dir: /www/
